### ISSUE TITLE
Improve controls and user experience

### ISSUE THREAD

**Issue by Dramloc** [Devotics/heatzy-home-hassistant#7]
As mentioned in issue #6, the Home Assistant component used for this project provides too many controls for the Heatzy Pilot : temperature display and control do not work as the Heatzy Pilot only support HVAC presets.

We should find a way to disable or hide these features to keep the component small and easy to use.

Another solution would be to find another Home Assistant platform that better fit the capabilities of the Heatzy Pilot.

I will try to find some solutions that work with the latest Home Assistant releases.

Ideas and inspirations are welcomed!

**Comment by Dramloc** [comment]
The default Home Assistant component does not seem flexible enough. The way to go might be to implement a custom lovelace card for the Heatzy Pilote. It could look something like this:

<img width="500" alt="Card" src="https://user-images.githubusercontent.com/4021308/69000978-6abd4080-08d7-11ea-9731-71f3de3690f6.png">

Buttons on the right will control the Pilote's preset (Off, Comfort, Eco and Away) and highlight the active preset.

This could also support multiple Pilotes in a single card:

<img width="500" alt="Card multiple entities" src="https://user-images.githubusercontent.com/4021308/69000988-8f191d00-08d7-11ea-8834-de2f9a03c07b.png">

And lovelace configuration could look like this:
```yaml
type: 'custom:heatzy-pilote-card'
entities:
  - climate.salon
  - climate.chambre
```

I will try to implement this after digging a bit into lovelace.

Let me know what you think!

**Comment by xdev-x** [comment]
Sounds great and it's look very nice !

**Comment by cbastienbaron** [comment]
can't wait to see it :)

**Comment by sebastien-k** [comment]
I'm trying to control my heaters with heatzy, but I haven't succeeded yet (I'm very new to Home Assistant, sorry if I made stupid mistakes).

I used this dedicated heatzy thermostat made by @benaisn instead of the home Assistant generic thermostat :
[https://github.com/benaisn/heatzy_thermostat](https://github.com/benaisn/heatzy_thermostat)

So I defined my **switch** in **configuration.yaml** :

```yaml
switch:
  - platform: template
    switches:
      radiateur_salle_de_bains:
        friendly_name: 'Radiateur Salle de Bains'
        icon_template: mdi:radiator
        value_template: "{{ is_state_attr('climate.salle_de_bains', 'operation_mode', 'heat') }}"
        turn_on:
          service: climate.set_operation_mode
          data:
            entity_id: climate.salle_de_bains
            operation_mode: 'heat'
        turn_off:
          service: climate.set_operation_mode
          data:
            entity_id: climate.salle_de_bains
            operation_mode: 'eco'
```
Then I defined my **generic_thermostat** in my **configuration.yaml** using that previous **switch**, as recommended by @benaisn :

```yaml
platform: generic_thermostat
  name: Thermostat Salle de Bains
  heater: switch.radiateur_salle_de_bains
  target_sensor: sensor.temperature_salle_de_bains
  min_temp: 17
  max_temp: 22
  ac_mode: false
  target_temp: 20
  initial_hvac_mode: "off"
  away_temp: 16
  hot_tolerance: 0
```

I made this card in my ui-lovelace.yaml :

```yaml
    - type: thermostat
      entity: climate.thermostat_salle_de_bains
```

I obtain this:
 
![image](https://user-images.githubusercontent.com/57752274/74067280-2da9ab80-49f9-11ea-9556-d61aa9de9e44.png)

this seems great BUT:

Even if I select higher temperature than current temp, like this:

![image](https://user-images.githubusercontent.com/57752274/74067246-166abe00-49f9-11ea-88f2-15336fa6c6f9.png)

(I want to reach 21.5 while it is actually 17.8), nothing happens, I was expecting my heater would turn on. But I might be wrong, so ok.

BUT:

if I press the "fire" icon, I obtain this:

![image](https://user-images.githubusercontent.com/57752274/74067411-7feacc80-49f9-11ea-83a2-561a6d6b5bcd.png)

and it says my heater is "Idle". I was expecting "Heating" instead.
Moreover, Home Assistant has no effect on the real heater.

So I don't understand what's wrong with my config, can someone help me?

Thanks in advance!

**Comment by benaisn** [comment]
@sebastien-k the preset modes have changed (I think last year)
now they are 
preset_modes: none,comfort,eco,away
So you need to replace 'heat' by 'comfort'

like that :

```yaml

  - platform: template
    switches:
      chauffage_salle_de_bain:
        friendly_name: 'Chauffage Salle de Bain'
        icon_template: mdi:radiator
        value_template: "{{ is_state_attr('climate.salle_de_bain', 'preset_mode', 'comfort') }}"
        turn_on:
          service: climate.set_preset_mode
          data:
            entity_id: climate.salle_de_bain
            preset_mode: 'comfort'
        turn_off:
          service: climate.set_preset_mode
          data:
            entity_id: climate.salle_de_bain
            preset_mode: 'away'

```

```yaml
  - platform: generic_thermostat
    name: Thermostat Salle de Bain
    heater: switch.chauffage_salle_de_bain
    target_sensor: sensor.oregon_salle_de_bain_temperature
    min_temp: 14
    max_temp: 22
    ac_mode: false
    target_temp: 18
    min_cycle_duration:
      seconds: 60
    away_temp: 14
    hot_tolerance: 0
    cold_tolerance: 0
    precision: 0.1
```

**Comment by sebastien-k** [comment]
@benaisn 

Thank you!
It works!

I made several mistakes, the one you said (replace 'heat' by 'comfort'), but also I had to replace 'operation_mode' by 'preset_mode'.

Thank again!

**Comment by omolko** [comment]
Hello 
thanks for the job done here.
I am very new with HA
At the moment I have my folder heatzy in custom_component, in my config.yaml I have put 
climate:
  platform: heatzy
  username: "olivier@*****"
  password: "J******8"
What should I do next? 
Thanks

**Comment by bikerman51** [comment]
> The default Home Assistant component does not seem flexible enough. The way to go might be to implement a custom lovelace card for the Heatzy Pilote. It could look something like this:
> 
> <img alt="Card" width="500" src="https://user-images.githubusercontent.com/4021308/69000978-6abd4080-08d7-11ea-9731-71f3de3690f6.png">
> 
> Buttons on the right will control the Pilote's preset (Off, Comfort, Eco and Away) and highlight the active preset.
> 
> This could also support multiple Pilotes in a single card:
> 
> <img alt="Card multiple entities" width="500" src="https://user-images.githubusercontent.com/4021308/69000988-8f191d00-08d7-11ea-8834-de2f9a03c07b.png">
> 
> And lovelace configuration could look like this:
> 
> ```yaml
> type: 'custom:heatzy-pilote-card'
> entities:
>   - climate.salon
>   - climate.chambre
> ```
> 
> I will try to implement this after digging a bit into lovelace.
> 
> Let me know what you think!

Hi ! 

Do you have done this card ?

**Comment by DanChaltiel** [comment]
Hi,

This integration is so awesome that I learned HomeAssistant integration just to make the above-mentioned card.

You can find it here: https://github.com/DanChaltiel/heatzy-pilote-card

![image](https://user-images.githubusercontent.com/15105152/102015208-7b4e1d80-3d5a-11eb-97f1-5b79b32d4da6.png)

@Dramloc any review or suggestion would be more than welcome!

**Comment by Dramloc** [comment]
Hi @DanChaltiel,
Thank you for your work, this seems awesome!

**Comment by Dramloc** [comment]
Hi,

Sorry for the delay on this issue, I won't have much time for this project in the future.
If anyone wants a custom card for the Heatzy Pilot, you can use the project created by @DanChaltiel: https://github.com/DanChaltiel/heatzy-pilote-card.

You can also create your own lovelace card if you want to customize the behavior. Here is a simple card example created using the lovelace editor:

![image](https://user-images.githubusercontent.com/4021308/110315551-b71b1b00-8009-11eb-8b10-98746b5153a4.png)


```yaml
type: vertical-stack
cards:
  - type: entity
    entity: climate.salon
    attribute: preset_mode
    icon: 'hass:none'
  - type: horizontal-stack
    cards:
      - type: button
        tap_action:
          action: call-service
          service: climate.set_preset_mode
          service_data:
            preset_mode: none
            entity_id: climate.salon
        entity: climate.salon
        show_state: false
        show_name: false
        show_icon: true
        icon: 'hass:do-not-disturb'
        hold_action:
          action: none
        icon_height: 24px
      - type: button
        tap_action:
          action: call-service
          service: climate.set_preset_mode
          service_data:
            preset_mode: comfort
            entity_id: climate.salon
        entity: climate.salon
        show_name: false
        icon_height: 24px
        hold_action:
          action: none
        show_state: false
        icon: 'hass:white-balance-sunny'
      - type: button
        tap_action:
          action: call-service
          service: climate.set_preset_mode
          service_data:
            preset_mode: eco
            entity_id: climate.salon
        entity: climate.salon
        icon: 'hass:leaf'
        show_name: false
        hold_action:
          action: none
        icon_height: 24px
      - type: button
        tap_action:
          action: call-service
          service: climate.set_preset_mode
          service_data:
            preset_mode: away
            entity_id: climate.salon
        entity: climate.salon
        icon: 'hass:snowflake'
        show_name: false
        hold_action:
          action: none
        icon_height: 24px
```
